In [88]:
import pandas as pd
import numpy as np
import geopandas as gpd

data = pd.DataFrame(
    columns=["code", "category", "area", "dwellings", "people", "state"]
)

for sheet in range(1, 13):
    sheet_data = pd.read_excel(
        "./MeshBlockCounts2021.xlsx",
        sheet_name=sheet,
        header=6,
        skipfooter=4
    )
    sheet_data.columns = data.columns
    data = pd.concat([data, sheet_data])
    print("sheet", sheet, "completed; length now", len(data))

sheet 1 completed; length now 59993
sheet 2 completed; length now 112738
sheet 3 completed; length now 172731
sheet 4 completed; length now 201477
sheet 5 completed; length now 261470
sheet 6 completed; length now 273339
sheet 7 completed; length now 301770
sheet 8 completed; length now 345092
sheet 9 completed; length now 358126
sheet 10 completed; length now 361487
sheet 11 completed; length now 368149
sheet 12 completed; length now 368285

In [87]:
test = data.copy()
test["dwellings"] = test["dwellings"].astype("float")
test["people"] = test["people"].astype("float")
test = test[
    (test["code"].apply(lambda x: str(x)[0] == "8")) &
    (test["area"] > 0)
]
test.groupby("category").sum()
# test.dtypes

                         area  dwellings    people
category
Commercial            26.3702     3840.0    6016.0
Education             18.0044      593.0    6665.0
Hospital/Medical       0.5807       59.0     487.0
Industrial            14.2237       12.0      74.0
Other                 32.8999        3.0      61.0
Parkland            1632.4028      275.0     587.0
Primary Production   421.8756      185.0     575.0
Residential          197.4942   182096.0  439276.0
Transport              2.0320        0.0      23.0
Water                 12.2495        0.0       0.0

In [91]:
mesh = gpd.read_file("./geodata/MB_2021_AUST_SHP_GDA2020.zip")
mesh

,MB_CODE21,MB_CAT21,CHG_FLAG21,CHG_LBL21,SA1_CODE21,SA2_CODE21,SA2_NAME21,SA3_CODE21,SA3_NAME21,SA4_CODE21,SA4_NAME21,GCC_CODE21,GCC_NAME21,STE_CODE21,STE_NAME21,AUS_CODE21,AUS_NAME21,AREASQKM21,LOCI_URI21,geometry
0,10000010000,Residential,0,No change,10901117207,109011172,Albury - East,10901,Albury,109,Murray,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,0.0209,http://linked.data.gov.au/dataset/asgsed3/MB/1...,"POLYGON ((146.92785 -36.08365, 146.92815 -36.0..."
1,10000021000,Commercial,0,No change,10901117612,109011176,Lavington,10901,Albury,109,Murray,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,0.0829,http://linked.data.gov.au/dataset/asgsed3/MB/1...,"POLYGON ((146.93543 -36.04752, 146.93722 -36.0..."
2,10000022000,Commercial,0,No change,10901117621,109011176,Lavington,10901,Albury,109,Murray,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,0.0388,http://linked.data.gov.au/dataset/asgsed3/MB/1...,"POLYGON ((146.93040 -36.04996, 146.93054 -36.0..."
3,10000023000,Commercial,0,No change,10901117621,109011176,Lavington,10901,Albury,109,Murray,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,0.0254,http://linked.data.gov.au/dataset/asgsed3/MB/1...,"POLYGON ((146.93254 -36.05238, 146.93101 -36.0..."
4,10000024000,Residential,0,No change,10901117613,109011176,Lavington,10901,Albury,109,Murray,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,0.0376,http://linked.data.gov.au/dataset/asgsed3/MB/1...,"POLYGON ((146.93044 -36.04733, 146.93036 -36.0..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368281,97000001777,SHIPPING,0,No change,99797979993,997979799,Migratory - Offshore - Shipping (OT),99797,Migratory - Offshore - Shipping (OT),997,Migratory - Offshore - Shipping (OT),99799,Migratory - Offshore - Shipping (OT),9,Other Territories,AUS,Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/MB/9...,"POLYGON ((105.66649 -10.42203, 105.66649 -10.4..."
368282,97000002777,SHIPPING,0,No change,99797979993,997979799,Migratory - Offshore - Shipping (OT),99797,Migratory - Offshore - Shipping (OT),997,Migratory - Offshore - Shipping (OT),99799,Migratory - Offshore - Shipping (OT),9,Other Territories,AUS,Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/MB/9...,"POLYGON ((96.88760 -12.11086, 96.88852 -12.110..."
368283,97000003777,SHIPPING,0,No change,99797979993,997979799,Migratory - Offshore - Shipping (OT),99797,Migratory - Offshore - Shipping (OT),997,Migratory - Offshore - Shipping (OT),99799,Migratory - Offshore - Shipping (OT),9,Other Territories,AUS,Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/MB/9...,"POLYGON ((167.97281 -29.01656, 167.97281 -29.0..."
368284,90000009499,NOUSUALRESIDENCE,0,No change,99999949999,999999499,No usual address (OT),99999,No usual address (OT),999,No usual address (OT),99499,No usual address (OT),9,Other Territories,AUS,Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/MB/9...,None
368285,ZZZZZZZZZZZ,Outside Australia,1,New,ZZZZZZZZZZZ,ZZZZZZZZZ,Outside Australia,ZZZZZ,Outside Australia,ZZZ,Outside Australia,ZZZZZ,Outside Australia,Z,Outside Australia,ZZZ,Outside Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/MB/Z...,None

In [102]:
qbn = ["101021610", "101021012", "101021009", "101021008", "101021009", "101021010"]
mesh = mesh[
    mesh["SA2_CODE21"].apply(lambda x: (x[0] == "8") | (x in qbn))
]
mesh[mesh["CHG_FLAG21"] == "1"]

,MB_CODE21,MB_CAT21,CHG_FLAG21,CHG_LBL21,SA1_CODE21,SA2_CODE21,SA2_NAME21,SA3_CODE21,SA3_NAME21,SA4_CODE21,SA4_NAME21,GCC_CODE21,GCC_NAME21,STE_CODE21,STE_NAME21,AUS_CODE21,AUS_NAME21,AREASQKM21,LOCI_URI21,geometry
108765,11211120000,Residential,1,New,10102161003,101021610,Googong,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,0.0348,http://linked.data.gov.au/dataset/asgsed3/MB/1...,"POLYGON ((149.23394 -35.42525, 149.23422 -35.4..."
108768,11211150000,Residential,1,New,10102161006,101021610,Googong,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,0.0384,http://linked.data.gov.au/dataset/asgsed3/MB/1...,"POLYGON ((149.24399 -35.42567, 149.24386 -35.4..."
108771,11211180000,Residential,1,New,10102161007,101021610,Googong,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,0.0261,http://linked.data.gov.au/dataset/asgsed3/MB/1...,"POLYGON ((149.23555 -35.42589, 149.23557 -35.4..."
108772,11211190000,Residential,1,New,10102161007,101021610,Googong,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,0.0205,http://linked.data.gov.au/dataset/asgsed3/MB/1...,"POLYGON ((149.23722 -35.42346, 149.23750 -35.4..."
108773,11211200000,Residential,1,New,10102161007,101021610,Googong,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,0.0190,http://linked.data.gov.au/dataset/asgsed3/MB/1...,"POLYGON ((149.23920 -35.42544, 149.23904 -35.4..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368142,85987000000,Primary Production,1,New,80104111702,801041117,Gungahlin - West,80104,Gungahlin,801,Australian Capital Territory,8ACTE,Australian Capital Territory,8,Australian Capital Territory,AUS,Australia,13.7405,http://linked.data.gov.au/dataset/asgsed3/MB/8...,"POLYGON ((149.14203 -35.14911, 149.14272 -35.1..."
368143,85988000000,Residential,1,New,80106113116,801061131,Kingston (ACT),80106,South Canberra,801,Australian Capital Territory,8ACTE,Australian Capital Territory,8,Australian Capital Territory,AUS,Australia,0.0634,http://linked.data.gov.au/dataset/asgsed3/MB/8...,"POLYGON ((149.14684 -35.31270, 149.14677 -35.3..."
368144,85989000000,Residential,1,New,80101114201,801011142,Macnamara,80101,Belconnen,801,Australian Capital Territory,8ACTE,Australian Capital Territory,8,Australian Capital Territory,AUS,Australia,4.2096,http://linked.data.gov.au/dataset/asgsed3/MB/8...,"POLYGON ((148.98289 -35.20585, 148.98296 -35.2..."
368145,85990000000,Residential,1,New,80101114401,801011144,West Belconnen,80101,Belconnen,801,Australian Capital Territory,8ACTE,Australian Capital Territory,8,Australian Capital Territory,AUS,Australia,2.0587,http://linked.data.gov.au/dataset/asgsed3/MB/8...,"POLYGON ((148.98289 -35.20585, 148.99247 -35.2..."
368146,85991000000,Residential,1,New,80106113106,801061131,Kingston (ACT),80106,South Canberra,801,Australian Capital Territory,8ACTE,Australian Capital Territory,8,Australian Capital Territory,AUS,Australia,0.0422,http://linked.data.gov.au/dataset/asgsed3/MB/8...,"POLYGON ((149.15088 -35.31449, 149.15076 -35.3..."